repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-yaml
    - id: check-json
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/streetsidesoftware/cspell-cli
  rev: v9.1.1
  hooks:
    - id: cspell # Spell check changed files
